# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_uploadfilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicCheckList',
        ),
    ]
